"""Upgrade Sprint model for planning wizard

Revision ID: b7c9466972c7
Revises: e28bd3c6f33f
Create Date: 2026-07-31 14:43:31.848275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7c9466972c7'
down_revision: Union[str, Sequence[str], None] = 'e28bd3c6f33f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('sprints', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('sprints', sa.Column('team_members', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sprints', sa.Column('velocity', sa.Integer(), nullable=True))
    op.add_column('sprints', sa.Column('story_points', sa.Integer(), nullable=True))
    op.add_column('sprints', sa.Column('ai_generated_plan', sa.Text(), nullable=True))
    op.add_column('sprints', sa.Column('timeline_suggestion', sa.Text(), nullable=True))
    op.add_column('sprints', sa.Column('risks_suggestion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprints', 'risks_suggestion')
    op.drop_column('sprints', 'timeline_suggestion')
    op.drop_column('sprints', 'ai_generated_plan')
    op.drop_column('sprints', 'story_points')
    op.drop_column('sprints', 'velocity')
    op.drop_column('sprints', 'team_members')
    op.drop_column('sprints', 'capacity')
    op.drop_column('sprints', 'duration')
    # ### end Alembic commands ###
