"""Add Requirement fields

Revision ID: e28bd3c6f33f
Revises: b1d14d56774f
Create Date: 2026-07-31 14:31:29.587927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28bd3c6f33f'
down_revision: Union[str, Sequence[str], None] = 'b1d14d56774f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('requirements', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('requirements', sa.Column('priority', sa.String(length=50), nullable=True))
    op.add_column('requirements', sa.Column('acceptance_criteria', sa.Text(), nullable=True))
    op.add_column('requirements', sa.Column('created_by_id', sa.UUID(), nullable=False))
    op.alter_column('requirements', 'generated_content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('requirements_generated_by_id_fkey'), 'requirements', type_='foreignkey')
    op.create_foreign_key(None, 'requirements', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'requirements', 'users', ['updated_by_id'], ['id'], use_alter=True)
    op.drop_column('requirements', 'generated_by_id')
    op.create_foreign_key(None, 'sprint_plans', 'users', ['updated_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'tasks', 'users', ['reporter_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'users', 'organizations', ['current_organization_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'sprint_plans', type_='foreignkey')
    op.add_column('requirements', sa.Column('generated_by_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'requirements', type_='foreignkey')
    op.drop_constraint(None, 'requirements', type_='foreignkey')
    op.create_foreign_key(op.f('requirements_generated_by_id_fkey'), 'requirements', 'users', ['generated_by_id'], ['id'])
    op.alter_column('requirements', 'generated_content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('requirements', 'created_by_id')
    op.drop_column('requirements', 'acceptance_criteria')
    op.drop_column('requirements', 'priority')
    op.drop_column('requirements', 'category')
    op.drop_column('requirements', 'description')
    # ### end Alembic commands ###
