"""Add AI PM fields to Project

Revision ID: e82ee5477cfb
Revises: 1ecb1814931c
Create Date: 2026-08-07 20:07:57.897375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82ee5477cfb'
down_revision: Union[str, Sequence[str], None] = '1ecb1814931c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_type', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('target_platform', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('expected_users', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('budget', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('tech_preferences', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'tech_preferences')
    op.drop_column('projects', 'budget')
    op.drop_column('projects', 'expected_users')
    op.drop_column('projects', 'target_platform')
    op.drop_column('projects', 'industry')
    op.drop_column('projects', 'project_type')
    # ### end Alembic commands ###
