"""Add agent_id and update members

Revision ID: f92ee5477cfb
Revises: e82ee5477cfb
Create Date: 2026-08-10 14:46:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92ee5477cfb'
down_revision: Union[str, Sequence[str], None] = 'e82ee5477cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('conversations')]
    if 'agent_id' not in columns:
        op.add_column('conversations', sa.Column('agent_id', sa.String(length=50), nullable=True, server_default='copilot'))
    op.execute("UPDATE organization_members SET status = 'accepted' WHERE role = 'owner' AND status = 'pending'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'agent_id')
    # ### end Alembic commands ###
