export type ActivityType = 
  | 'Task Created' | 'Task Updated' | 'Task Deleted' | 'Task Assigned' | 'Task Completed'
  | 'Sprint Generated' | 'Sprint Approved'
  | 'SRS Generated' | 'SRS Approved'
  | 'Document Uploaded' | 'Document Processed'
  | 'Comment Added'
  | 'Project Created'
  | 'Member Invited' | 'Role Changed'
  | 'AI Conversation' | 'AI Draft Updated';

export interface ActivityLog {
  id: string;
  type: ActivityType;
  userName: string;
  userInitials: string;
  timestamp: string;
  description: string;
  taskRef?: string;
  documentRef?: string;
}

export const mockActivity: ActivityLog[] = [
  {
    id: "act-1",
    type: "Document Uploaded",
    userName: "Alex Dev",
    userInitials: "AD",
    timestamp: "Just now",
    description: "Uploaded System_Architecture_V1.pdf",
    documentRef: "System_Architecture_V1.pdf"
  },
  {
    id: "act-2",
    type: "Task Completed",
    userName: "Alex Dev",
    userInitials: "AD",
    timestamp: "2 hours ago",
    description: "Completed task 'Setup FastAPI Repo'",
    taskRef: "T-4"
  },
  {
    id: "act-3",
    type: "Sprint Approved",
    userName: "Sarah PM",
    userInitials: "SP",
    timestamp: "Yesterday, 3:45 PM",
    description: "Approved the 3-sprint roadmap generated by AI."
  },
  {
    id: "act-4",
    type: "AI Draft Updated",
    userName: "AI Assistant",
    userInitials: "AI",
    timestamp: "Yesterday, 3:30 PM",
    description: "Updated the Planning Draft based on feedback."
  },
  {
    id: "act-5",
    type: "SRS Approved",
    userName: "Sarah PM",
    userInitials: "SP",
    timestamp: "Oct 24, 2026",
    description: "Approved the Software Requirements Specification."
  },
  {
    id: "act-6",
    type: "Project Created",
    userName: "System",
    userInitials: "SY",
    timestamp: "Oct 20, 2026",
    description: "Created the new project workspace."
  }
];
